# Site Settings
title: Coder. Activist. Learner.
email: melaniejane.pascual@gmail.com
description: website and blog
url: "www.melaniejanepascual.com"
twitter_username: mjpasx		
github_username:  melaniejanepascual
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM