# Site settings
title:        Melanie Jane Pascual
subtitle:     test
description:  This is the jekyllTheme example blog. It only exists to demonstrate how the theme looks and feels.
language:     "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:      "" # the subpath of your site, e .g. /blog
url:          "http://www.melaniejanepascual.com" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:    /blog/:categories/:title
cover:        /assets/mountain-cover.jpg

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from